### ISSUE TITLE
Yläpalkissa oleva sivuston nimi vaatii hiomista

### ISSUE THREAD

**Issue by mtijas** [Kentsuuu93/kokija.tiko2020.trade#10]
Sivuston nimen tulisi:

- [x] Keskittyä pystysuunnassa
- [x] Olla sopivan kokoinen jokaiseen sivukokoon
- [x] Olla jollain sopivalla fontilla kirjoitettu (jos ei sitten nykyinen ole hyväksi katsottava)
- [x] Olla kivan värinen ja ehkä omata pieni varjostus

**Comment by mtijas** [comment]
@MarkusMurto Mikäs on k-logon fontti, jos koitan työntää samaa headeriin?

**Comment by mtijas** [comment]
Oli nähtävästi Salsa, tai ainakin se on erittäin lähellä. Laitoin sen nyt toistaiseksi.

**Comment by MarkusMurto** [comment]
Kyllä, se on Salsa, mikäli info on vielä hyödyksi.
