### ISSUE TITLE
Tarvitaanko sivuston yläpalkissa K-logoa lainkaan?

### ISSUE THREAD

**Issue by mtijas** [Kentsuuu93/kokija.tiko2020.trade#12]
Pidetäänkö K-logo sivuston yläpalkissa, vai jätetäänkö se vain faviconiksi? Mielestäni logoa ei yläpalkissa tarvita, sillä se ei tuo mitään lisää sivustolle. Yläpalkkia ja/tai sivuston taustaa voisi kuvittaa ennemmin isolla taustakuvalla tai vastaavasti.

**Comment by MarkusMurto** [comment]
Olen samaa mieltä, että ei ole tarpeellinen. Teinkin sen alunperin faviconiksi.

Pelkkä yrityksen nimi on ihan tyylikäs itsekseen yläpalkissa.

**Comment by MarkusMurto** [comment]
Logon tilalla voisikin olla se hampurilaismenun painike (#9) kapeammassa näkymässä.

**Comment by mtijas** [comment]
Mielestäni se dev-haarassa sivun nimellä nyt oleva fontti Salsa on itse asiassa varsin hyvin toimiva. Mennään vaikka toistaiseksi sillä, jos ei muita ideoita tule.

Yleisesti ottaen sivuston navigaatiota ei kannata hampurilaismenunakaan sijoittaa vasempaan ylänurkkaan, sillä se on tyypillisesti logon paikka, eivätkä kävijät osaa mieltää nettisivuilla vasemmassa yläkulmassa olevia asioita muuksikaan. Toisaalta kun päävalikko on nyt oikeassa ylänurkassa, tulisi hampurilaismenunkin olla siellä, jottei päävalikko ns. hypi ympäri näyttöä. Käytettävyyden kannalta sinänsä paras paikka päävalikolle nettisivulla on yläpalkissa heti logon oikealla puolella, tai sitten vasemmassa laidassa heti logon alapuolella jos valikko on pystysuuntainen.

Haara https://github.com/Kentsuuu93/kokija.tiko2020.trade/tree/ei-liikemerkkia näyttää sivuston ilman K-logoa (joka siis on oikeasti liikemerkki, kun on tuommoinen graafinen asia ilman tekstiä / nimeä. Logo on tyylitelty tekstinpätkä (firman nimi), ja liiketunnus sitten taas liikemerkki + logo yhdessä :D)

![image](https://user-images.githubusercontent.com/41751327/105552292-60cd7380-5d0c-11eb-933f-b5c5a3e9e6bb.png)

**Comment by MarkusMurto** [comment]
Jes, mennään tällä meikäläisen puolesta! Jonkinlainen liikemerkki tai logo voidaan tosiaan harkita myöhemmin mikäli sellaista halutaan ja silloin se voisi olla jotain muuta kuin K-kirjain tosiaan.

Mutta juu tosiaan oikealla se menun painike sopii myös. Pointtinani oli lähinnä se, että kapeammalla näytöllä siinä tilaa vapautuu sille painikkeelle, kun tuota ei ole.

**Comment by mtijas** [comment]
Jees, mergesin tuon haaran deviin, niin saadaan tuo pelkkä logo käyttöön. Liikemerkki voidaan tosiaan kehittää sitten eri issuessa jos tarvitaan. Suljen tämän, sillä K-merkki oli alun perinkin tarkoitettu vain faviconiksi, ja sen tuonti headeriin oli minulta ihan vain testimielessä tehty juttu.
