### ISSUE TITLE
Navigaatiomenu kapeamalle näkymälle

### ISSUE THREAD

**Issue by MarkusMurto** [Kentsuuu93/kokija.tiko2020.trade#13]
Omaan silmääni linkkien asettuminen kahdelle riville ei näytä kovinkaan kivalta (kuvakaappaus `ei-liikemerkkia`-haarasta):
![screenshot](https://i.imgur.com/MRJMEGd.png)

Toteutuksella ei tässä vaiheessa ole vielä minusta väliä, mutta aikaisemmin on ollut issueissa ja tapaamisissa puhetta hampurilaismenusta.

**Comment by mtijas** [comment]
Kannatan toteutusta CSS-hampurilaismenulla tai jollain muulla puhtaan CSS:n ratkaisulla.
