### ISSUE TITLE
Tuotantopalvelin antaa virheen 500 kun sivua ei löydy

### ISSUE THREAD

**Issue by mtijas** [Kentsuuu93/kokija.tiko2020.trade#14]
Tuotantopalvelin antaa, virheen 404 sijaan, virheen 500 kun sivua ei löydy.

## Toistettavuus:

1. Mene urliin [https://kokija.tiko2020.trade/palvelut.html](https://kokija.tiko2020.trade/palvelut.html), tai mille tahansa muulle päävalikon sivulle kuin index.html.
2. Saat virheen 500 Internal Server Error.

**Comment by MarkusMurto** [comment]
Tutkitaan!

**Comment by MarkusMurto** [comment]
Jes nyt pitäisi antaa 404 niinkuin pitää. Vian aiheutti configiin jäänyt ylimääräinen rivi, kun config oli alkujaan kopioitu toisen palvelin sivuston configista.
