### ISSUE TITLE
Tulisiko sivuston koon lakata kasvamasta suurimmassa breakpointissa?

### ISSUE THREAD

**Issue by mtijas** [Kentsuuu93/kokija.tiko2020.trade#16]
Mielestäni sivuston leveyden tulisi lakata kasvamasta isoimmassakoossaan, mutta mitä mieltä muut olette? 

Esimerkkinä maksimileveydestä voisi olla joku hieman reilu tuhat pikseliä, esimerkiksi 80 em (eli 1280 px).

**Comment by MarkusMurto** [comment]
Mielestäni myös tulisi, luettavuuskin heikkenee kun rivipituus kasvaa.

**Comment by mtijas** [comment]
Sivustolle asetettu maksimileveys 80 rem (1280 px).
