### ISSUE TITLE
Painike hampurilaismenun sulkemiseen

### ISSUE THREAD

**Issue by MarkusMurto** [Kentsuuu93/kokija.tiko2020.trade#17]
Kun hampurilaismenu on kerran avattu, sen saa suljettua vain klikaamalla jotakin menun vaihtoehtoa.

Olisiko jonkinlainen X-painike hampurilaismenuun mielekäs?

**Comment by mtijas** [comment]
Pitäisi kyllä sulkeutua, kun klikkaa menun alapuolella johonkin. Näyttää itse asiassa siltä, että puhtaalla css:llä tällaisen valikon toteuttaminen ei ole läheskään niin helppo homma kuin JS:llä. Yksi vaihtoehto on vaihtaa avauspainikkeeksi checkbox (jätin sen nyt toistaiseksi tarkoituksella käyttämättä), ja lisätä koko sivuston päälle näkymätön div, jota klikkaamalla checkboxin raksi poistetaan. Checkbox itsessään toki voisi näyttää tuolta kuten nytkin, tai joltain muultakin.

Nykyisen ratkaisun valitsin siis puhtaasti siksi, että html:ään ei tule ylimääräisiä elementtejä, mutta siinä on rajoitteena tuo valikon sulkemisongelma. Sen lisäksi nykyinen ratkaisu vaatii puolen sekunnin viiveen valikon sulkeutumiseen, jotta valikon klikkaus ehtii rekisteröityä ennen valikon sulkeutumista (valikko kun näkyy käytännössä vain, kun Menu-painikkeella on focus, ja focus lähtee linkkiä klikatessa pois ennen, kuin klikkaus ns. menee perille -> ilman viivettä valikon elementtejä ei voisi klikata).

Tuo on nyt ihan mielenkiintoinen selvittää, saako valikon sulkeutumaan ilman ylimääräistä diviä, ja toisaalta toimiiko mobiilissa sittenkään kunnolla.

**Comment by mtijas** [comment]
Lisäkommenttina todettakoon vaikka, että oikeissa töissä valikon avaus ja sulkeminen kannattaa toteuttaa JS:llä (ei tarvitse kuitenkaan kuin pari riviä vanilla-js:ää), ja fallbackina näyttää koko valikko jatkuvasti, jos JS:ää ei ole käytössä. Helpoin ratkaisu, toimii kaikilla käytettävästi, ja nopeahko tehdä.

**Comment by MarkusMurto** [comment]
Hmm kokeilinkin että hiirellä klikkaamalla ohi hampurilaisvalikko menee kiinni, mutta mobiilissa ohi napauttamalla se ei suljeudu kuitenkaan.

**Comment by mtijas** [comment]
Okei, mulla sulkeutui kaikilla vehkeillä kyllä (iPhone 8 [Safari & Edge], iPad mini 5 [Edge] ja Lumia 735. Pitänee vielä testailla noilla Androideilla, miten ne tykkäävät.

**Comment by MarkusMurto** [comment]
Nyt toimii iOS Safarilla myös ohi täppääminen.
