### ISSUE TITLE
Tulisiko logoa klikkaamalla käyttäjä linkata etusivulle?

### ISSUE THREAD

**Issue by MarkusMurto** [Kentsuuu93/kokija.tiko2020.trade#18]
Käyttäjillä on usein selkärangassa se toiminto, että sivuston logoa klikkaamalla päästään etusivulle.

**Comment by mtijas** [comment]
Kyllä tulisi. Hoidan samalla, kun aloin hioa tuota ulkoasua muutenkin sieltä täältä.
