### ISSUE TITLE
site-content marginaalit tuntuvat pieniltä

### ISSUE THREAD

**Issue by MarkusMurto** [Kentsuuu93/kokija.tiko2020.trade#19]
Luulen, että luettavuutta parantaisi, mikäli marginaaleja kasvatettaisiin. Tällä hetkellä teksti tuntuu olevan turhan reunassa "paperiarkilla".
![screenshot](https://i.imgur.com/GJ8R6Wm.png)

**Comment by mtijas** [comment]
Sisällön paddingeja kasvatettu, ja tehty responsiivisiksi.
