### ISSUE TITLE
Yhteystiedot eivät asetu pystysuunnassa asianmukaisesti

### ISSUE THREAD

**Issue by MarkusMurto** [Kentsuuu93/kokija.tiko2020.trade#20]
Yhteystiedot nähtävästi pyrkii keskittymään samalla grid-rivillä olevan kappaleen kanssa. Tämä näkyy erityisen hyvin kapeassa näkymässä
![screenshot](https://i.imgur.com/f1Oeg3S.png)
Tarkoituksena oli saada yhteystiedot asettumaan omassa grid-osiossaan järkevästi alkamaan suoraan otsikon jälkeen. Yritin tätä korjata, mutta en meinannut löytää CSS-sääntöä, joka tämän korjaisi.

**Comment by mtijas** [comment]
Vilkaisen tätä vielä tänään.

**Comment by mtijas** [comment]
Noin, katsoin ja puukotin "vähän" :dagger: 

Haara yhteystiedot-issue-20 sisältää kaikki muutokset, ja commit-viesteissä selitykset niille. Yritin pitää commitit myös jotenkin järkevän kokoisina, jotta muutoksia olisi helpompaa seurata.

**Comment by MarkusMurto** [comment]
Kiitoksia! Se näyttää hyvältä! Tässä näyttää kovasti siltä että tuolla webbikurssilla en oppinut kaikkea tarvittavaa :D sen eväillä tosiaan tätä lähdin rakentamaan.
Puolestani voi mergeä dev-haaraan.

**Comment by mtijas** [comment]
Joo, sieltä tuli hädin tuskin perusteet :D.
