### ISSUE TITLE
Mikä on desktop.ini-tiedoston tarkoitus?

### ISSUE THREAD

**Issue by MarkusMurto** [Kentsuuu93/kokija.tiko2020.trade#21]
Commitissa b8d2a079 hakemiston juureen ilmestyi tämä tiedosto - ilmeisesti vahingossa?
Voidaanko tämä poistaa?

**Comment by mtijas** [comment]
Kyllä voidaan poistaa. Kyseessä on Windowsin Explorerin tapa tallentaa käyttäjän kansionäkymä (järjestys, näkymän muoto yms). Kannattaisi lisätä myös .gitignoreen, jotta ei tule enää uusiksi.

**Comment by MarkusMurto** [comment]
.gitignore lisätty.
