### ISSUE TITLE
Palvelut-sivun kuvakarusellin vauhtia voisi hidastaa

### ISSUE THREAD

**Issue by mtijas** [Kentsuuu93/kokija.tiko2020.trade#22]
Palvelut-sivun kuvakaruselli pyörii sen verran nopeasti, että kuvien katsomiselle ei varsinaisesti jää aikaa. 5-10 sekuntia per kuva, riippuen siinä yhteydessä luettavan tekstin määrästä, on yleensä hyvä aika. Aikaa olisi mielestäni hyvä jättää tällaisessa käyttötarkoituksessa riittävästi, jotta kävijä ehtii kuvaa katsoessaan hetken haaveilla, että "tuonne minäkin haluan".

Tässäkin karusellissa voisi lisäksi yhdistää jokaiseen kuvaan pienen pätkän kuvatekstiä herättämään kävijän mielenkiinnon kuvassa olevaa kohdetta kohtaan, jotta kävijä sitten haluaa lähteä käymään siellä (oman issuensa aihe, jos teksti halutaan toteuttaa).

**Comment by MarkusMurto** [comment]
Voin tutkia tuota hidastamista ainakin.
