### ISSUE TITLE
Annukanhommelit kansiossa tuotteet tiedostoon on lisatty kaikki sinne tulevat "tavarat", kommentteja?

### ISSUE THREAD

**Issue by Ankinen** [Kentsuuu93/kokija.tiko2020.trade#24]
Tein nyt ensimmaisen raakaversion tuotteet tiedostosta. Pitaisi lisata sinne nyt kaikkea ulkonakoon vaikuttavaa. Esim. Deveja en ole tehnyt viela yhtaan.

Jostain syysta en Bashissa saanut tehtya committia, mahdoinkohan tehda oikein, ilmoitti, etta ei ole mitaan committoitavaa...

**Comment by mtijas** [comment]
Yhden commitin olet ainakin kolmisen tuntia sitten tehnyt, joten joku on onnistunut. Mitä `git fetch` ja sen jälkeen `git status` näyttää siellä omassa haarassasi, onko commitoitavaa?

**Comment by Ankinen** [comment]
git status
On branch annukanhommelit
nothing to commit, working tree clean

**Comment by Ankinen** [comment]
gitHub desktop näyttää commitit

**Comment by Ankinen** [comment]
Tein GitHub desktopissa lopulta Commitin, eli se saattaa olla se, joka meni läpi

**Comment by mtijas** [comment]
Jeps, muutokset on tosiaan commitoitu ihan oikein, yhtä kautta commitoitu riittää kunhan `git status` näyttää sen jälkeen tuon "nothing to commit, working tree clean". Tämäpä se läpi mennyt sitten on: https://github.com/Kentsuuu93/kokija.tiko2020.trade/commit/25ed9562bb4558cbb3d381742697aca0a16ce3f2

**Comment by Ankinen** [comment]
Joo, tein siis tuon GitHub desktop commitoinnin **sen jälkeen** kun batch väitti, että ei ole mitään commitoitavaa. Mutta pääasia on, että jotain on mennyt jonnekin.

**Comment by mtijas** [comment]
Saattaisi olla käynyt niin, että commit on itse asiassa mennyt läpi paikallisesti jo aiemmin, ja github desktop on vain tehnyt pushin lopulta. Tai sitten jotain muuta, mutta kyllä se ajan ja ihmettelyn myötä pikkuhiljaa selkenee :)

**Comment by mtijas** [comment]
Tein nyt jonkin verran muutoksia, toki lähinnä tuota sisällön asettelua paikoilleen. Mielestäni tämän sprintin osalta voidaan mennä tällä, ja jatketaan hienosäätöä sitten seuraavassa sprintissä.

**Comment by mtijas** [comment]
Nyt on tosiaan tämä haara mergetty deviin, joten seuraava kehitystyö kannattaa tehdä omaan uuteen haaraansa. Suljen siis tämän issuen, ja avataan uusia taas sitä mukaa, kun asioita ilmenee.
