### ISSUE TITLE
Sivuston kuvien optimointi

### ISSUE THREAD

**Issue by MarkusMurto** [Kentsuuu93/kokija.tiko2020.trade#25]
Sivustolla käytettävät kuvatiedostot olisi hyvä saada tarkoituksenmukaisen pieniksi.

Toimenpiteet kuvatiedostoille:
- [x] resoluutiota laskettu
- [x] pakattu uudelleen webp-formaattiin

**Comment by mtijas** [comment]
Lisäksi sivuston kuvien pikselikokoja tulisi harkita, ja kuvien näkyviä korkeuksia myös. Nyt moni kuvista on alkuperäisessä kuvasuhteessaan aivan suhteettoman korkea paikkaansa.
