### ISSUE TITLE
Projektisuunnitelman ja KoKiJa sivun yhteystiedot yhdenmukaisiksi

### ISSUE THREAD

**Issue by Ankinen** [Kentsuuu93/kokija.tiko2020.trade#27]
Projektisuunnitelma löytyy Teamsistä. 

Etusivun alaosassa ja Yhteystietosivulla olisi hyvä olla sama osoite. Samoin Projektisuunnitelmassa olisi varmaan hyvä olla samat tiedot.

**Comment by mtijas** [comment]
Yhteystiedot muutettu ilmiselvästi keksityiksi sekä sivustolle että projektisuunnitelmaan. Emme halua julkinetissä olevan sivuston kanssa (tai muutenkaan) vahingossakaan tilannetta, jossa sivustoa tai siihen liittyvää yritystä voisi luulla oikeaksi, saati että sivustolta vahingossa linkattaisi mihinkään mahdollisille tulevaisuudessa tehtäville sivustoille (siksi valitsin sähköpostiosoitteiden muodoksi `@domain.tld`, se tuskin ihan heti tulee käyttöön minnekään).
