### ISSUE TITLE
Tuotesivuilla tuotekuvat voisivat olla isolla näytöllä huomattavasti pienempiä

### ISSUE THREAD

**Issue by Ankinen** [Kentsuuu93/kokija.tiko2020.trade#29]
Jokin sellainen koko, etteivät ne veisi hirvittävästi paljoa enempää tilaa, mitä teksti.

**Comment by mtijas** [comment]
Joidenkin kuvien kohdalla voisi ajatella samalla tarkempia ja rankkojakin rajauksia, jotta saadaan ne riittävän mataliksi.

**Comment by MarkusMurto** [comment]
Kokeilen näitä samalla kun muutenkin alan pelaamaan kuvien kanssa.

**Comment by MarkusMurto** [comment]
7e793a2 saattoi auttaa tässäkin.

**Comment by mtijas** [comment]
Mielestäni kuvat ovat nyt aivan hyviä, joten suljen tämän.
