### ISSUE TITLE
Main-haara tuotantohaaraksi: poistetaan prod-haara

### ISSUE THREAD

**Issue by mtijas** [Kentsuuu93/kokija.tiko2020.trade#3]
Main-haaraa ei nähdäkseni tarvita kehitysprosessissamme, joten sen voisi poistaa tarpeettomana. Tämä on alun perin @MarkusMurto'n esille tuoma asia, loin sen tänne kun liittyy suoraan kehitysasioihin.

**Comment by mtijas** [comment]
Teams-kommentin perusteella avaan tämän uudelleen, toteutetaan kunhan ollaan ensin vähän harjoiteltu gitin käyttöä tällaisenaan. Kts. milestone johon tämä on merkitty toteutukseen.

[maanantaina 12.47] Murto Markus
    Harmi vaan että REUSE API tsekkaa tuon default-haaran, joka ei tietenkään ole spesifikaation mukainen, niin sitä nättiä badgea ei saada README:een.

**Comment by mtijas** [comment]
Toisaalta main-haaraa käytetään usein tuotantohaarana, joten vaihtoehtoinen lähestymistapa on poistaa prod-haara. Ei mitään väliä sinänsä, molemmat vaihtoehdot tuottavat käytännössä saman lopputuloksen.

**Comment by MarkusMurto** [comment]
Tämäkin käy. Siinäkin sit pääsee harjoittelemaan, jos vahingossa main-haaraan menee dev-haaraan tarkoitettuja committeja :D 

@Kentsuuu93 voi poistaa prod-haaran kun kerkeää.

**Comment by Kentsuuu93** [comment]
Prod haara poistettu
