### ISSUE TITLE
Yhteystietosivun lomake ei ole täysin responsiivinen

### ISSUE THREAD

**Issue by Ankinen** [Kentsuuu93/kokija.tiko2020.trade#30]
Huawei Mate 10 lite, android. Yhteystietosivu vuotaa vasemmalta
![Kokijayhteystiedot](https://user-images.githubusercontent.com/75733422/106728264-f32b1c80-6614-11eb-9a74-7b7613213456.jpg)

**Comment by mtijas** [comment]
Ah, vähän näyttää, että joku lomake-elementti (kenties textarea) jää liian leveäksi. Toisena huomiona sisällön vasen padding voisi olla vähän pienempi. Pitääpä kaivaa tuo Android-kapula esille ja testailla itsekin ehtiessään.

**Comment by MarkusMurto** [comment]
Sama homma näyttäisi olevan myös iOS-Safarissa, iPhone SE (2020) iOS 14.4
![kuvakaappaus](https://i.imgur.com/hC95S1j.png)

**Comment by mtijas** [comment]
Näyttää toistuvan myös firefoxilla, joten on helpompi debugata. Löysin jo vian, korjailen ihan tuota pikaa.

**Comment by mtijas** [comment]
Jes, ja korjattu toivottavasti riittävässä laajuudessa, ja pushattu deviin tarkempaa testausta varten.
