### ISSUE TITLE
Kielivalintalippujen lisenssi-informaatio on tarkistettava

### ISSUE THREAD

**Issue by mtijas** [Kentsuuu93/kokija.tiko2020.trade#31]
Kielivalintalippujen lisenssi-informaatio on hatusta heitetty, joten se tulisi tarkistaa. Ovat käytännössä Wikimediasta public domain -lisenssillä, mutta eipä harmi kyllä aavistustakaan, mitä tuohon .reuse/dep5-tiedostoon tulisi asiasta ilmaista.

**Comment by mtijas** [comment]
https://commons.wikimedia.org/wiki/File:Flag_of_Finland.svg ja https://en.wikipedia.org/wiki/File:Flag_of_the_United_Kingdom.svg

**Comment by MarkusMurto** [comment]
`Copyright`-rivi on periaatteessa vapaamuotoinen, mutta mikäli tekijä on tiedossa, se sopisi siihen asettaa. Laitan tässä tapauksessa saman mitä Wikipedia/Wikimedia on tekijöiksi merkannut eli sekä vektoripiirtäjän että valtion.
Sekä REUSE että `copyright/debian` vaatii kuitenkin että tähän jotakin laittaa, joten tyhjäksikään ei voi jättää vaikka laki ei mainintaa vaadikaan. 

`License`-riville tässä tapauksessa `LicenseRef-public-domain` on asianmukainen, kun kyseessä on näin julkisia teoksia. Esimerkiksi `CC0-1.0` periaatteessa on tarkoitettu alkuperäisen omistajan julistettavaksi. Tässä kantsii tehdä "custom"-lisenssitiedosto, jossa sitten vaan lukee, että kyseessä on public domain teos. [Tästä](https://wiki.creativecommons.org/wiki/PDM_FAQ#What_is_the_difference_between_the_PDM_and_CC0.3F) voi tutustua tarkemmin, jos kiinnostaa.
(Koska kyseessä on custom-lisenssi, alkuun tarvitaan tuo `LicenseRef-`)

**Comment by MarkusMurto** [comment]
Oikeastaan halutessaan nämä tiedostot olisi voinut yhtä hyvin olla mainitsematta dep5:ssa, sillä Public Domain -teoksia voidaan vapaasti uudelleenlisensoida vaikka MIT-lisenssillä - kuten villikortilla dep5:ssa onkin määritelty.

**Comment by mtijas** [comment]
Meinasin itse asiassa alun perin jättää nuo liput pois dep5:stä, mutta ajattelin sen olevan vähän tympeää, ja samalla toisaalta opetella miten tämä toimii. Kiitos kattavasta selityksestä ja ratkaisusta, seuraavan lisenssi/tekijänoikeustiedon saatankin osata jo tuon perusteella laittaa kuntoon itsekin :)

**Comment by MarkusMurto** [comment]
Jes (: vielä tarkennan aikaisemmin kirjoittamaani, että tuo custom-lisenssi tehdään tosiaan silloin, kun tarvittavaa lisenssiä [SPDX](https://github.com/spdx/license-list-data/tree/master/text) ei tunne. Sitten vaan tosiaan siihen viitataan `LicenseRef-LISENSSI` ja sitä vastaava lisenssiteksti LICENSES-hakemistoon `LicenseRef-LISENSSI.txt`

Luultavasti tuon `public-domain`:n löysit [`debian/copyright`-dokumentaatiosta](https://dep-team.pages.debian.net/deps/dep5/#license-specification), mutta se hauska tuossa onkin, että `debian/copyright`:ssa kans ajateltu, että se public domain kans pitää mainita, vaikka SPDX ei sitä tunne - mutta kuitenkaan sitä ei tuohon dokumentaatioon ole merkitty SPDX:n mukaisesti `LicenseRef-public-domain`. Tästä sitten `reuse lint` herjaa.

**Comment by mtijas** [comment]
Jep, tuoltahan sen tosiaan löysin. Sinänsä vähän ihmettelinkin, että miksei SPDX sitä tunne, koska olisihan se hyvä joka tapauksessa mainita (kommunikoidakseen sen, että lisenssiä on kuitenkin ajateltu, eikä vain varastettu). Vaikka koko public domain nyt "epälisenssi" onkin. 

Mietin itse asiassa tuota LicenseRef-alkuosan ymppäämistä dep5:een jo alusta lähtien, mutta en keksinyt, mihin se sitten varsinaisesti viittaisi. En viitsinyt lisenssitekstiä alkaa tosiaan itse keksiä, kun oletin, että "jostain" löytyy jokin valmiskin teksti jota pitäisi käyttää, enkä vain ollut tähän kaninkoloon niin pitkälle vielä tipahtanut.

Vaikuttaa eittämättä varsin hyvälle tämä reuse. Taidan ottaa itsellekin käyttöön omiin juttuihin, jos nyt jotain oikeasti julkaistavaa joskus tekee.
