### ISSUE TITLE
Prettierin ajo kaikille html- ja css-tiedostoille projektin lopuksi

### ISSUE THREAD

**Issue by mtijas** [Kentsuuu93/kokija.tiko2020.trade#33]

**Comment by MarkusMurto** [comment]
`yhteystiedot.html` ja `contacts.html` done.

**Comment by Ankinen** [comment]
Mie oonkin tuota Prettieriä käyttänyt koko ajan, välillä se ei kyllä tee kovin pretty, mutta se onkin mielipidekysymys...

**Comment by mtijas** [comment]
Molemmat index-sivut, header ja footer done.

**Comment by MarkusMurto** [comment]
Tsekkasin, että molemmat palvelusivut on myös ok.

**Comment by mtijas** [comment]
Tuotteet-sivut myös ok, kaikki ok, suljetaan.
