### ISSUE TITLE
Palvelut-sivun kurssikorttien kuvien optimointi

### ISSUE THREAD

**Issue by MarkusMurto** [Kentsuuu93/kokija.tiko2020.trade#35]
Kurssikortit näyttää muuten mielestäni valmiilta, mutta kuvat vielä puuttuu.

**Comment by Ankinen** [comment]
Anteeksi tyhmyyteni, mutta miten lisään kuvat tänne? Ne ovat nyt saatavilla Teamsissä.

**Comment by MarkusMurto** [comment]
Ne img-taseissa viitatut kuvat lisätään siis sinne img-hakemistoon, jonne niihin siinä tagissa viittasitkin.

**Comment by Ankinen** [comment]
äh, huomiokykyni on jotenkin viallinen. Eilen en löytänyt mistään mitään nappulaa, josta saa uploadattua tiedostoja. Ehkä ne nyt ovat siellä?

**Comment by MarkusMurto** [comment]
Ne siis lisätään sinne git-repoon samalla tapaa kuin muutkin tiedostot, jonka jälkeen
```
git add .
git commit -m "Lisätty kuvia"
```
näin esimerkiksi.  Eli samat temput miten muutenkin repoon jotain lisättäessä, kuvien kohdalla tämä ei poikkea.

**Comment by Ankinen** [comment]
Voi jee, lisäsin ne täältä hubin kautta suoraan uploadaamalla mainiin, eli en tehnyt kyllä nyt oikein :/

**Comment by MarkusMurto** [comment]
Okei kokeiles uusiksi lisätä ne ihan komentorivillä omaan haaraasi.

**Comment by Ankinen** [comment]
Kokeilen. Markus Ijäs siirsi ne dev haaraan (käsittääkseni)

**Comment by Ankinen** [comment]
Missä ne kuvat pitäisi olla, että ne saa lisättyä? Ne on nyt minun koneellani kuvat kansiossa eli ei missään gitiin liittyvässä paikassa...

**Comment by MarkusMurto** [comment]
Jes ne menivät sinne sun haaraan. Voin optimoida ne myöhemmin tänään, ellet sinä niitä optimoi.

Ne kuvat oli siis tarkoitus lisätä sinne samaan hakemistoon, jossa se git-repokin on. Sieltä löytyy tämä `www/img`-hakemisto.

**Comment by Ankinen** [comment]
Yritin lisätä kuvia, mutta git valitti... mutta juu, ne on jo pieniä, en oo varma ovatko tarpeeksi pieniä. Enkä kyllä ole ihan varma, miten niitä optimoit, joten parempi, että sinä teet sen... (Ehkä)

**Comment by MarkusMurto** [comment]
Ovat toki mukavan pieniä, mutta webp-pakkauksella saadaan vielä pienemmäksi.

**Comment by Ankinen** [comment]
Aaa, en ajatellut niin pitkälle tuota optimointia. jos saat sen helposti tehtyä, niin tee vaan.

**Comment by mtijas** [comment]
Kuvat devissä, tosin jpg. Sieltä sitten jos haluttaa optimoida :)

**Comment by MarkusMurto** [comment]
Jes hieno homma! Tsekkaan illemmalla nämä.

**Comment by MarkusMurto** [comment]
Taitaakin olla sen verran pieniä jeepeggiä, että uudelleenpakkaaminen ei enää kannata, vaan sillä saa vaan aikaan artifakteja tässä koossa. Mennään vain näillä.
