### ISSUE TITLE
Palvelut sivut valmis?

### ISSUE THREAD

**Issue by Ankinen** [Kentsuuu93/kokija.tiko2020.trade#36]
Käsittääkseni palvelut sivujen suomenkielinen versio on valmis. Ellette sitten vielä kekkaa jotain saavutettavuusjuttua, mikä siitä puuttuu. Kuvia en osannut lisätä oikeaan kansioon (miten se tehdään?). Ne ovat saatavilla Teamsissä.
Jos tämä on nyt OK, niin voisin aamusta tekaista sen englanninkielisen version.

**Comment by mtijas** [comment]
Siirrän kurssikorttien kuvat main-haarasta tänne, jotta voidaan testata niitä ennen tuotantoon vientiä.

**Comment by mtijas** [comment]
Tämä valmis. Avataan kuvien muuttamiselle webp:ksi uusi issue, jos nähdään tarpeelliseksi.
