### ISSUE TITLE
English version Palvelut sivuista tehty, onko OK?

### ISSUE THREAD

**Issue by Ankinen** [Kentsuuu93/kokija.tiko2020.trade#38]
Tein tuon enkun kielisen version palvelut sivuista, toivottavasti meni OK, vähän mämmäilin kaiken kanssa alkuun, mutta uskoisin, että se toimii nyt!

Ilmoitelkaa asap, jos tarvii vielä tehdä jotain

**Comment by mtijas** [comment]
Noin, mergetty ja pushattu deviin.
