### ISSUE TITLE
Sivuston kuvien saavutettavuudessa on ongelmia

### ISSUE THREAD

**Issue by mtijas** [Kentsuuu93/kokija.tiko2020.trade#39]
# Etusivulla
## Kuvien nimet eivät ole kuvaavia (WCAG 2.1: 1.1.1)
- img/etusivufigure1.webp
- img/etusivufigure2.webp

# Palvelut-sivulla
## Kuvien nimet ja alt-tekstit eivät ole kuvaavia (WCAG 2.1: 1.1.1)
- /img/karuselli1.webp alt="Maisemakuva"
- /img/karuselli2.webp alt="Maisemakuva"
- /img/karuselli3.webp alt="Maisemakuva"
- /img/karuselli4.webp alt="Maisemakuva"
- /img/karuselli5.webp alt="Maisemakuva"

https://www.saavutettavuusvaatimukset.fi/digipalvelulain-vaatimukset/wcag-2-1/

**Comment by MarkusMurto** [comment]
@Ankinen onko ideoita, miten laitettaisiin?

**Comment by mtijas** [comment]
Korjattu etusivun kuvien osalta

**Comment by MarkusMurto** [comment]
Karuselli kunnossa

**Comment by mtijas** [comment]
Tämä ok

**Comment by Ankinen** [comment]
Katsoin tuota ja mietin, pitäisikö ne nimetä jotenkin muuten. Mutta ilmeisesti saitte asian hoidettua.
