### ISSUE TITLE
GIT-repo tulisi asettaa julkiseksi

### ISSUE THREAD

**Issue by MarkusMurto** [Kentsuuu93/kokija.tiko2020.trade#4]
Lainattu Sprint 1 backlogista:

> Yrityksen it-päällikkönä haluan, että www-sivuston toteutuksessa käytetään GIT-versionhallintaohjelmistoa, jotta kehitys on hallittua ja voin seurata sitä

Jotta repossa kehitystä asiakas voisi näppärästi seurata, repo tulisi asettaa julkiseksi.

**Comment by Kentsuuu93** [comment]
Repon pitäisi olla nyt public.
