### ISSUE TITLE
Joistain painikkeista ei käy ilmi mitä niistä tapahtuu

### ISSUE THREAD

**Issue by mtijas** [Kentsuuu93/kokija.tiko2020.trade#41]
- Palvelut-sivuilla kurssikorttien "ilmoittaudu mukaan" painikkeista tulisi selvitä aria-labelilla, mille kurssille ilmoittaudutaan.
- Tuotteet-sivuilla tilaa-napeissa tulisi olla aria-labelit kertomassa mitä napista tilataan

WCAG 2.1: 2.4.4. https://www.saavutettavuusvaatimukset.fi/digipalvelulain-vaatimukset/wcag-2-1/ 

https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA8

**Comment by mtijas** [comment]
Tuotteet-sivuille lisätty aria-labelit

**Comment by MarkusMurto** [comment]
Palvelut-sivuille lisätty aria-labelit

**Comment by mtijas** [comment]
Tämä ok

**Comment by Ankinen** [comment]
Kiitos tästä!
