### ISSUE TITLE
Kielivalinta lippu on tooooooodella suuri

### ISSUE THREAD

**Issue by Ankinen** [Kentsuuu93/kokija.tiko2020.trade#42]
Se pitäisi korjata, mistä se korjataan?

**Comment by murtoM** [comment]
En pysty kyllä toistamaan. Koeta päivittää ohittaen välimuisti Ctrl+Shift+R

**Comment by mtijas** [comment]
Selain tosiaan välimuistittaa, ctrl+f5 auttaa.
