### ISSUE TITLE
Tyyliopas & tyylimuotoilija

### ISSUE THREAD

**Issue by MarkusMurto** [Kentsuuu93/kokija.tiko2020.trade#5]
Toivoisin, että kehitystä lähdettäisiin tekemään jonkin järkevän tyylioppaan mukaisesti. Onko tähän ehdotuksia hyviin HTML ja CSS tyylioppaisiin?

Varmaan olisi ainakin hyvä määrittää edes, että esimerkiksi koodia sisennetään kahdella välilyönnillä ja rivipituus ei pääse 80:a merkkiä suuremmaksi.

**Comment by mtijas** [comment]
Kannatan jonkin tyylioppaan valintaa, tai ainakin tosiaan sisennystä kahdella välilyönnillä ja rivinpituutta 80 soft limit ja 100 hard limit.

Ehdotan tyylioppaaksi Prettierin vakiomuotoiluja mukaillen Googlen [HTML/CSS Style Guiden](https://google.github.io/styleguide/htmlcssguide.html) mukaisiksi niiltä osin, joita Prettier ei jo noudata (en tiedä onko sellaisia). Prettierille voidaan tehdä VSCoden pluginille projektikohtainen konfiguraatio .prettierrc, joten lienee varsin simppeli lopulta. Kts: https://itnext.io/keep-code-consistent-across-developers-the-easy-way-with-prettier-eslint-60bb7e91b76c.

**Comment by MarkusMurto** [comment]
Tuo Googlen tyyliopas näyttä ihan fiksulta. Mites Prettierin kanssa kannattaa toimia? Kannattaako sen antaa muokata tiedostoja ihan vapaasti?

**Comment by mtijas** [comment]
En ainakaan tähän mennessä ole nähnyt siitä mitään haittaa. Yleensä tosin en pidä automaattiformatointia päällä, vaan teen nätityksen manuaalisesti ennen tallennusta. Voisi olla järkevää laittaa nätitys tallennuksessa päälle kyllä.

**Comment by mtijas** [comment]
Ah, täältähän ne näkee nuo Prettierin oletukset, vaikuttaa äkkiseltään aikalailla Googlen tyyliopasta vastaaville: https://prettier.io/docs/en/options.html. Tuo Prettier on tosiaan siitä vähän meh, että ei voi ihan tuosta vaan käskeä sen käyttää vaikkapa Googlen opasta lähteenään (tai ainakaan en vielä tiedä, että miten). Mutta en sitten tiedä, onko se mikään oikea ongelma. Voidaan myös valita joku toinen formatoija, jos joku muu on parempi. Ainut mitä haluaisin, niin että se olisi VSCode-yhteensopiva.

**Comment by MarkusMurto** [comment]
Joo itselleni nämä formatoijat ei ole lainkaan tuttuja, niin paha itse ehdottaa parempaa ratkaisua. Kokeilin Prettieriä komentorivillä ja vaikka siinä on epämiellyttäviä juttuja (_mm. asennetaan npm:llä_) niin kyllä se näyttää ihan toimivan.

VSCode-yhteensopivuus on varmaan hyvä olla, koska sitä suurin osa tiimistä luultavasti käyttää.

Jos Prettieriin päädytään, voisi sitten täydentää miten se otetaan VSCodessa käyttöön, kun lisäilin tästä oman sivun OneNoteen.

**Comment by MarkusMurto** [comment]
Jes mennään mun puolesta tällä! Issue voidaan vaikka avata uusiksi, jos siltä tuntuu.
