### ISSUE TITLE
Faviconin design

### ISSUE THREAD

**Issue by MarkusMurto** [Kentsuuu93/kokija.tiko2020.trade#8]
Voisin toki lisätä sivustolle jonkin yksinkertaisen faviconin, esimerkiksi:
![Favicon](https://i.imgur.com/WUJ0hya.png)

Mutta onko @Ankinen:lla yrityksen keksijänä jonkinlaista visiota sivuston ulkoasusta? 

Faviconin olisi hyvä suunnitella tämän kanssa sopivaksi.

**Comment by Ankinen** [comment]
Minulla ei ole mitään ajatusta. Yritän etsiä tänään illalla kuvia, joita voidaan liittää sivulle. Ongelmana on tosiaan, että ne ovat aivan sekaisin ja osasta kuvia en edes tiedä mistä ne ovat. Vanhan läppärin kiintolevy sanoi sopimuksensa irti ennen kuin ehdin siirtää kaikki kuvat turvaan ja ne on pelastettu siitä levystä mutta pelastusoperaatio ei säilyttänyt hakemistoja, joissa luki, milloin ja mistä kuvat on otettu. Olen siis asunut 10 vuotta Kiinassa ja Hongkongissa, niin kuvia on aika läjä. Tosin alkuajoista on enemmän kuvia, kun silloin kaikki oli uutta ja ihmeellistä. Mutta katsotaan, mitä tuolta kaaoksesta löytyy.

Mutta siis, ehkä noista kuvista tulee joku idea teillekin?

**Comment by Ankinen** [comment]
Ai niin, olenko ymmärtänyt oikein, että tänne GitHubiin itse asiassa kannattaisi tallentaa ne kuvat?

**Comment by MarkusMurto** [comment]
Lisätään tänne ne kun ollaan katsottu mitä kuvia halutaan sivulle ja sitten ne lisättäisiin. Kaikkia ei tänne tarvi eikä pidä laittaa, vaan ne mitä käytetään.

Mutta Teams-varmaan hyvä paikka mihin voi loittaa kuvia karsittavaksi ja tutkittavaksi ennen Githubiin siirtämistä.

**Comment by MarkusMurto** [comment]
Mutta tosiaan tuossa ehdottamassani simppleissä oli sentään hiukan ajatusta mukana: valitsin punaisen värin kun punainen esiintyy niin Kiinan, Hong Kongin, Taiwanin ja Japanin lipuissa sekä ymmärtääkseni punainen väri ei ole epätavallinen kiinalaisessa arkkitehtuurissa.

**Comment by Ankinen** [comment]
En tajunnut, että tuo oli tyyliehdotus. Anteeksi ymmärtämättömyyteni. Minusta ihan hieno, tausta voisi olla tumma, mutta ei ehkä välttämättä aivan musta, joku tumman harmaa saattaisi toimia myös. Siis, jos toi musta tausta kuului myös kuvaan...

**Comment by MarkusMurto** [comment]
En tiedä miten se kuva sinulla näkyy, mutta K-kirjaimen takana on tarkoitus olla punainen neliö pyöristetyillä kulmilla ja nämä kulmat olisi tarkoitus läpinäkyviä.

**Comment by MarkusMurto** [comment]
Jes keskusteltiin tästä Teams:ssä ja tällä voidaan lähteä.
