### ISSUE TITLE
Navigaatiolinkit pienimmässä breakpointissa asettuu hölmösti

### ISSUE THREAD

**Issue by MarkusMurto** [Kentsuuu93/kokija.tiko2020.trade#9]
Pienimmässä breakpointissa linkit voisi mahdollisesti olla hampurilaismenussa?

**Comment by mtijas** [comment]
4da35178a7c74903d038a33218a621d74664f0ef korjaa tätä huomattavasti. Kts. issue #10. Ei kuitenkaan tuota hampurilaisvalikkoa, joka voisi silti olla järkevää toteuttaa.

**Comment by MarkusMurto** [comment]
Hampurilaismenu voisi selkeyden vuoksi olla omassa issuessaan.
